apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: app-data-reader@dfuseio-global.iam.gserviceaccount.com
  name: app-data-reader
  namespace: sol-mainnet